# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CD <- function(x, y, beta, toler, maxit, tau, lambda) {
    .Call('_QR_CD', PACKAGE = 'QR', x, y, beta, toler, maxit, tau, lambda)
}

QRPMMCPP <- function(xr, y, beta, toler, maxit, tau, lamda) {
    .Call('_QR_QRPMMCPP', PACKAGE = 'QR', xr, y, beta, toler, maxit, tau, lamda)
}

